# Generated by Django 5.1.7 on 2025-06-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskflowapp', '0005_project_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
