# Generated by Django 5.1.7 on 2025-06-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskflowapp', '0011_teammember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
