# Generated by Django 5.1.7 on 2025-06-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskflowapp', '0012_delete_teammember_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
